ALTER VIEW VW_RASTREAMENTO AS SELECT  B.ZZ4_IDEQU, 
	B.ZZ4_IDMOV,
	B.ZZ4_FILIAL,
	(CASE WHEN B.ZZ4_FILIAL = '0101' THEN 'BLM'
		 WHEN B.ZZ4_FILIAL = '0102' THEN 'MAO'
		 WHEN B.ZZ4_FILIAL = '0103' THEN 'STM'
		 WHEN B.ZZ4_FILIAL = '0104' THEN 'PTR'
	END) ZZ4_NOMFIL,
	B.ZZ4_PORTAL,
	(CASE WHEN B.ZZ4_PORTAL = '1' THEN 'PORTARIA'
	  WHEN B.ZZ4_PORTAL = '2' THEN 'PORTO'
	END) ZZ4_NOMPOR,
	Z2.ZZ2_NOMPES ZZ2_NOMPES,
	Z2.ZZ2_EMPPES ZZ2_EMPPES,
	Z3.ZZ3_PLACA ZZ3_PLACA,
	Z3.ZZ3_FROTA ZZ3_FROTA,
	Z3.ZZ3_NUMEQU ZZ3_NUMEQU,
	Z3.ZZ3_EMPEQU ZZ3_EMPEQU,
	Z3.ZZ3_TIPEQU ZZ3_TIPEQU,
	date_format(B.ZZ4_DATMOV,'%d/%m/%y') AS ZZ4_DATMOV,
	B.ZZ4_HORMOV ZZ4_HORMOV, 
	(CASE	WHEN ZZ4_TIPMOV = '1' 
		THEN 'NO PATIO' 
		ELSE 'EM TRANSITO' 
	END) AS ZZ4_STATUS,
	DATEDIFF(date(now()),date(ZZ4_DATMOV)) AS DIAS,
	Z3.ZZ3_POSSE ZZ3_POSSE
FROM VW_EQUMAXDATHOR A
	INNER JOIN ZZ4 B 
    	ON B.ZZ4_IDEQU=A.ZZ4_IDEQU 
       AND CONCAT(B.ZZ4_DATMOV,B.ZZ4_HORMOV)=A.MAXDATHOR
	LEFT JOIN ZZ2 Z2 ON Z2.ZZ2_IDPES = B.ZZ4_IDPES
	LEFT JOIN ZZ3 Z3 ON Z3.ZZ3_IDEQU = B.ZZ4_IDEQU
WHERE B.D_E_L_E_T_<> '*' AND B.ZZ4_IDEQU <>''